### ISSUE TITLE
Unable to load draco gltf file

### ISSUE THREAD

**Issue by devhims** [belivvr/aframe-react#82]
Hi @juunini  and team,

While I didn't encounter any issues in loading non-compressed gltf/glb files, I couldn't load Draco compressed gltf files. Have you faced any similar issues? 

I've added `draco_decoder.js`, `draco_decoder.wasm`, and `draco_wasm_wrapper.js` files in the public folder and set my scene like this: 

```
  <Scene gltf-model='dracoDecoderPath: /'>
      <Camera id='camera' position={{ x: 0, y: 4, z: 10 }}></Camera>
      <Light type='ambient' intensity='1'></Light>
      <Entity
        id='model'
        gltf-model='/fox.glb'
        position={{ x: 0, y: 0, z: 0 }}
        scale={{ x: 15, y: 15, z: 15 }}
      ></Entity>
      <Plane
        color='#7BC8A4'
        id='ground'
        rotation={{ x: -90, y: 0, z: 0 }}
        width='20'
        height='20'
        shadow
      />
      <Sky color='#ECECEC' />
    </Scene>
```

I'm getting the following error: 

![Screenshot 2022-10-19 at 2 39 36 AM](https://user-images.githubusercontent.com/17825870/196545426-7e4b473b-1f59-4d85-9654-be286523f2f9.png)

Can you please help me?

**Comment by juunini** [comment]
Umm... I think you fix `gltf-model` to `gltfModel` in Entity tag.

or, how about use [types-aframe-react](https://github.com/juunini/types-aframe-react)?
