### ISSUE TITLE
How to register components in Aframe using Nextjs?

### ISSUE THREAD

**Issue by pemonter** [belivvr/aframe-react#84]
I'm trying to create a VR scene using Aframe, and I want to register a custom Aframe component, with click events, as in the example.

I tried this:

```tsx
import type { NextPage } from 'next';

import React, { useEffect, useState } from 'react';
import {
  Scene,
  Box,
  Sky,
  Sphere,
  Cylinder,
  Plane
} from '@belivvr/aframe-react';

const Home: NextPage = () => {
  const [rendered, setRendered] = useState<boolean>(false);


  function register() {
    AFRAME.registerComponent('spinner', {
      schema: {
        dur: { type: 'number' },
        startEvent: { type: 'array' },
        position: { type: 'vec3' },
        spin: { type: 'boolean' },
      },

      init() {
        // ...
      },
    });
  }

  useEffect(() => {
    setRendered(true);
    if (typeof window !== 'undefined') {
      require('aframe');
      register();
    }
  }, []);

  if (!rendered) {
    return <>loading</>;
  }

  return (
    <Scene>
      <Box
        spinner={{
          dur: 2000,
          startEvent: ['click', 'mouseenter'],
          position: { x: 0, y: 0, z: -1 },
          spin: true,
        }}
        position={{ x: -1, y: 0.5, z: -3 }}
        rotation={{ x: 0, y: 45, z: 0 }}
        color="#4CC3D9"
      />
      <Sphere
        position={{ x: 0, y: 1.25, z: -5 }}
        radius={1.25}
        color="#EF2D5E"
      />
      <Cylinder
        position={{ x: 1, y: 0.75, z: -3 }}
        radius={0.5}
        height={1.5}
        color="#FFC65D"
      />
      <Plane
        position={{ x: 0, y: 0, z: -4 }}
        rotation={{ x: -90, y: 0, z: 0 }}
        width={4}
        height={4}
        color="#7BC8A4"
      />
      <Sky color="#ECECEC" />
    </Scene>
  );
};

export default Home;
```

But the click or mouseenter event does not reproduce as expected. How to fix it?

**Comment by juunini** [comment]
you should insert property `cursor="rayOrigin: mouse;"` in Scene tag

**Comment by pemonter** [comment]
> you should insert property `cursor="rayOrigin: mouse;"` in Scene tag

The error I got was that the "spinner" was already registered, and that there couldn't be two components with the same name. This happened due to React's StrictMode. Once that was done and as recommended, the scene was rendered, but the expected functionality of click or mouseenter did not work.

**Comment by pemonter** [comment]
> you should insert property `cursor="rayOrigin: mouse;"` in Scene tag

The error I got was that the "spinner" was already registered, and that there couldn't be two components with the same name. This happened due to React's StrictMode. Once that was done and as recommended, the scene was rendered, but the expected functionality of click or mouseenter did not work.
